fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
# hex_literal_case = "Lower"
max_width = 80
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
struct_variant_width = 80
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
