[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
chainbills = "381yy2z6SFe7prqkF55WWnerFE19w6Fb5AfxcYhm2R78"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/obumnwabude/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
