[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
chainbills = "7YWuy7VkB76uJXt8xHaQu8aGWodG7NUaCkmzVFWg94xk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/obumnwabude/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
