[toolchain]
anchor_version = "0.32.1"

[features]
seeds = true
skip-lint = false

[programs.devnet]
chainbills = "DWhfdyzTiD2Jpkh3FhS2PreTSraqh3jWGfiTAoFG5wNk"

[programs.mainnet]
chainbills = "DWhfdyzTiD2Jpkh3FhS2PreTSraqh3jWGfiTAoFG5wNk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "RUST_LOG=ERROR cargo test -p chainbills && npm test -- --verbose"
