#!/usr/bin/env node
// Copies the generated chainbillsAbi to the backend and frontend consumers.
// Run `pnpm abi:export` first (or use `pnpm abi:publish` which chains both).
//
// Writes:
//   ../backend/src/chains/abi/chainbills.ts  - backend copy with its header comment
//   ../frontend/src/stores/chainbills-abi.ts - frontend export with its header comment

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = join(ROOT, 'abi', 'chainbills.ts');

let source;
try {
  source = readFileSync(SOURCE, 'utf8');
} catch (cause) {
  throw new Error(`abi/chainbills.ts not found — run 'pnpm abi:export' first`, { cause });
}

// Strip the bare export line; the content is everything after the first '= '
// The file is: export const chainbillsAbi = [...] as const;\n
const arrayStart = source.indexOf(' = ');
if (arrayStart === -1) throw new Error('unexpected abi/chainbills.ts format');
const arrayBody = source.slice(arrayStart + 3); // "[...] as const;\n"

const BACKEND_HEADER = `\
// ──────────────────────────────────────────────────────────────────────────────
// Chainbills Backend — Chainbills diamond ABI
//
// Verbatim copy generated by evm/script/export-abi.mjs from IChainbills (the
// aggregate interface). Do not edit by hand: run \`pnpm abi:publish\` in evm/
// to refresh both this file and the frontend copy.
//
// Invariants:
//   - This is the only ABI the backend uses — no legacy mainAbi / gettersAbi.
//   - src/chains/abi/abi-sync.spec.ts compares this copy against
//     evm/abi/chainbills.json when that file exists (skipped otherwise).
// ──────────────────────────────────────────────────────────────────────────────

export const chainbillsAbi = ${arrayBody}`;

const FRONTEND_HEADER = `\
// ──────────────────────────────────────────────────────────────────────────────
// Chainbills diamond ABI
//
// Generated by evm/script/export-abi.mjs from IChainbills (the aggregate
// interface). Do not edit by hand: run \`pnpm abi:publish\` in evm/ to refresh.
// ──────────────────────────────────────────────────────────────────────────────

export const chainbillsAbi = ${arrayBody}`;

const backendDest = join(ROOT, '..', 'backend', 'src', 'chains', 'abi', 'chainbills.ts');
const frontendDest = join(ROOT, '..', 'frontend', 'src', 'stores', 'chainbills-abi.ts');

writeFileSync(backendDest, BACKEND_HEADER);
writeFileSync(frontendDest, FRONTEND_HEADER);

console.log(`Published chainbillsAbi to:`);
console.log(`  backend/src/chains/abi/chainbills.ts`);
console.log(`  frontend/src/stores/chainbills-abi.ts`);
